from .search import SearchSkill
from .login import LoginSkill
from .form_fill import FormFillSkill
from .upload import UploadSkill
from .download import DownloadSkill
from .navigation import NavigationSkill
from .pagination import PaginationSkill
from .popup import PopupSkill
from .table_reader import TableReaderSkill
from .infinite_scroll import InfiniteScrollSkill