// frontend/src/components/DeliveryOptions.jsx
// Shows after execution is complete — user chooses where to send code

import { useState } from 'react';

export default function DeliveryOptions({ userId, code, goal, language, output }) {
  const [loading,     setLoading]     = useState(null); // which button is loading
  const [repoResult,  setRepoResult]  = useState(null);
  const [error,       setError]       = useState('');
  const [githubUser,  setGithubUser]  = useState(null);

  // ── Check GitHub connection on mount ──
  useState(() => {
    fetch(`/api/github/status/${userId}`)
      .then(r => r.json())
      .then(d => { if (d.connected) setGithubUser(d.username); })
      .catch(() => {});
  }, [userId]);

  // ── Connect GitHub ──
  const connectGitHub = async () => {
    const res  = await fetch(`/api/github/connect/${userId}`);
    const data = await res.json();
    if (data.url) window.location.href = data.url; // redirect to GitHub OAuth
  };

  // ── Push to GitHub ──
  const pushToGitHub = async () => {
    setLoading('github');
    setError('');
    try {
      const repoName = goal
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, '')
        .trim()
        .split(' ')
        .slice(0, 4)
        .join('-') || 'mcis-project';

      const ext = language === 'python' ? 'py'
                : language === 'typescript' ? 'ts'
                : language === 'java' ? 'java'
                : 'js';

      const res = await fetch('/api/github/push', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userId,
          repoName,
          description: `Generated by MCIS: ${goal}`,
          files: [
            { path: `main.${ext}`, content: code },
            { path: 'README.md',   content: `# ${repoName}\n\nGenerated by MCIS\n\n## Goal\n${goal}\n\n## Output\n\`\`\`\n${output}\n\`\`\`` },
          ],
        }),
      });

      const data = await res.json();
      if (!data.success) throw new Error(data.error);
      setRepoResult(data);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(null);
    }
  };

  // ── Open in Colab (Python only) ──
  const openInColab = () => {
    const nb = {
      nbformat: 4,
      nbformat_minor: 5,
      metadata: { kernelspec: { display_name: 'Python 3', language: 'python', name: 'python3' } },
      cells: [
        {
          cell_type: 'markdown',
          metadata:  {},
          source:    [`# ${goal}\n\nGenerated by MCIS`],
        },
        {
          cell_type: 'code',
          metadata:  {},
          source:    [code],
          outputs:   [],
          execution_count: null,
        },
      ],
    };

    const blob = new Blob([JSON.stringify(nb)], { type: 'application/json' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = 'mcis_notebook.ipynb';
    a.click();
    URL.revokeObjectURL(url);
  };

  // ── Copy to clipboard ──
  const copyCode = () => {
    navigator.clipboard.writeText(code);
  };

  if (!code) return null;

  return (
    <div style={styles.container}>
      <h3 style={styles.title}>🚀 Deliver Your Code</h3>
      <p style={styles.subtitle}>Choose where you want to use this code</p>

      <div style={styles.grid}>

        {/* ── GitHub / VS Code ── */}
        <div style={styles.card}>
          <div style={styles.cardIcon}>🐙</div>
          <h4 style={styles.cardTitle}>GitHub + VS Code</h4>
          <p style={styles.cardDesc}>Push to your GitHub repo and open in VS Code</p>

          {!githubUser ? (
            <button style={styles.btn} onClick={connectGitHub}>
              Connect GitHub
            </button>
          ) : (
            <button
              style={{ ...styles.btn, background: '#238636' }}
              onClick={pushToGitHub}
              disabled={loading === 'github'}
            >
              {loading === 'github' ? 'Pushing...' : `Push to @${githubUser}`}
            </button>
          )}

          {repoResult && (
            <div style={styles.result}>
              <a href={repoResult.repoUrl} target="_blank" rel="noreferrer" style={styles.link}>
                🔗 View on GitHub
              </a>
              <a href={repoResult.vsCodeUrl} style={styles.link}>
                💻 Open in VS Code
              </a>
              <a href={repoResult.codespacesUrl} target="_blank" rel="noreferrer" style={styles.link}>
                ☁️ Open in Codespaces
              </a>
            </div>
          )}
        </div>

        {/* ── Jupyter / Colab ── */}
        {language === 'python' && (
          <div style={styles.card}>
            <div style={styles.cardIcon}>📓</div>
            <h4 style={styles.cardTitle}>Jupyter / Colab</h4>
            <p style={styles.cardDesc}>Download as .ipynb and open in Jupyter or Google Colab</p>
            <button style={{ ...styles.btn, background: '#F9AB00', color: '#000' }} onClick={openInColab}>
              Download .ipynb
            </button>
            <p style={styles.hint}>Then drag & drop to <a href="https://colab.research.google.com" target="_blank" rel="noreferrer" style={styles.link}>colab.research.google.com</a></p>
          </div>
        )}

        {/* ── Copy Code ── */}
        <div style={styles.card}>
          <div style={styles.cardIcon}>📋</div>
          <h4 style={styles.cardTitle}>Copy Code</h4>
          <p style={styles.cardDesc}>Copy to clipboard — paste anywhere you want</p>
          <button style={{ ...styles.btn, background: '#334155' }} onClick={copyCode}>
            Copy Code
          </button>
        </div>

      </div>

      {error && <p style={styles.error}>❌ {error}</p>}
    </div>
  );
}

const styles = {
  container: { marginTop: 24, padding: 20, background: '#0f172a', borderRadius: 12, border: '1px solid #1e293b' },
  title:     { color: '#f1f5f9', fontSize: 18, marginBottom: 4 },
  subtitle:  { color: '#64748b', fontSize: 13, marginBottom: 20 },
  grid:      { display: 'flex', gap: 16, flexWrap: 'wrap' },
  card:      { flex: '1 1 200px', background: '#1e293b', borderRadius: 10, padding: 16, display: 'flex', flexDirection: 'column', gap: 8 },
  cardIcon:  { fontSize: 28 },
  cardTitle: { color: '#f1f5f9', fontSize: 15, margin: 0 },
  cardDesc:  { color: '#94a3b8', fontSize: 12, margin: 0, lineHeight: 1.5 },
  btn:       { background: '#6366f1', color: '#fff', border: 'none', borderRadius: 8, padding: '8px 16px', fontSize: 13, cursor: 'pointer', fontWeight: 600, marginTop: 4 },
  result:    { display: 'flex', flexDirection: 'column', gap: 6, marginTop: 8 },
  link:      { color: '#7dd3fc', fontSize: 12, textDecoration: 'none' },
  hint:      { color: '#64748b', fontSize: 11, margin: 0 },
  error:     { color: '#fca5a5', fontSize: 13, marginTop: 12 },
};